# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 迢迢
owner:
  name: ccandbb17
  email: ccandbb17@gmail.com
  github: ccandbb17
  weibo: 5893545128


# Site description
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  This is ccandbb17's Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ccandbb17.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
